@api = http://localhost:3000/api/products

{{api}}

### add a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "product 10",
    "price": 10,
   "description": "some product",
   "quantity": 14
}

### get product
{{api}}/11

### delete product 
DELETE {{api}}/100

### get count
{{api}}/count

### update
PUT {{api}}/9
Content-Type: application/json

{
    "name": "laptop",
    "price": 30,
    "description": "some laptop",
    "quantity": 20
}